export type SiteImageSlotDefinition = {
  key: string;
  label: string;
  pageTitle: string;
  sectionLabel: string;
  usageLabel: string;
  route: string;
  fallbackUrl: string;
  fallbackAlt: string;
  groupKey: string;
  groupLabel: string;
  groupDescription: string;
};

export const SITE_IMAGE_SLOTS: SiteImageSlotDefinition[] = [
  {
    key: 'home.hero.main',
    label: 'Главная — главный экран',
    pageTitle: 'Главная',
    sectionLabel: 'Первый экран',
    usageLabel: 'Фоновое изображение на первом экране главной страницы',
    route: '/',
    fallbackUrl: '/images/home_page/hero.png',
    fallbackAlt: 'Производственная студия Credomir',
    groupKey: 'home',
    groupLabel: 'Главная страница',
    groupDescription: 'Основные изображения главной страницы.',
  },
  {
    key: 'home.portfolio.som',
    label: 'Главная — портфолио СОМ',
    pageTitle: 'Главная',
    sectionLabel: 'Блок «Портфолио»',
    usageLabel: 'Первая карточка примеров работ на главной странице',
    route: '/',
    fallbackUrl: '/images/home_page/examples_of_work/som.png',
    fallbackAlt: 'Рекламная стела для СОМ',
    groupKey: 'home',
    groupLabel: 'Главная страница',
    groupDescription: 'Основные изображения главной страницы.',
  },
  {
    key: 'home.portfolio.nevinnomyssk',
    label: 'Главная — портфолио Невинномысск',
    pageTitle: 'Главная',
    sectionLabel: 'Блок «Портфолио»',
    usageLabel: 'Вторая карточка примеров работ на главной странице',
    route: '/',
    fallbackUrl: '/images/home_page/examples_of_work/nevinnomyssk.png',
    fallbackAlt: 'Въездная стела Невинномысск',
    groupKey: 'home',
    groupLabel: 'Главная страница',
    groupDescription: 'Основные изображения главной страницы.',
  },
  {
    key: 'home.portfolio.apple',
    label: 'Главная — портфолио Apple Time',
    pageTitle: 'Главная',
    sectionLabel: 'Блок «Портфолио»',
    usageLabel: 'Третья карточка примеров работ на главной странице',
    route: '/',
    fallbackUrl: '/images/home_page/examples_of_work/apple.png',
    fallbackAlt: 'Световой лайтбокс Apple Time',
    groupKey: 'home',
    groupLabel: 'Главная страница',
    groupDescription: 'Основные изображения главной страницы.',
  },
  {
    key: 'services.card.baget',
    label: 'Услуги — багет',
    pageTitle: 'Услуги',
    sectionLabel: 'Карточка услуги',
    usageLabel: 'Изображение карточки «Багетная мастерская» (главная + страница услуг)',
    route: '/services',
    fallbackUrl: '/images/services/bagget.png',
    fallbackAlt: 'Багетная мастерская',
    groupKey: 'services-cards',
    groupLabel: 'Карточки услуг',
    groupDescription: 'Картинки карточек услуг, используются на главной и странице услуг.',
  },
  {
    key: 'services.card.cnc',
    label: 'Услуги — фрезеровка',
    pageTitle: 'Услуги',
    sectionLabel: 'Карточка услуги',
    usageLabel: 'Изображение карточки «Фрезеровка листовых материалов»',
    route: '/services',
    fallbackUrl: '/images/services/milling.png',
    fallbackAlt: 'Фрезеровка листовых материалов',
    groupKey: 'services-cards',
    groupLabel: 'Карточки услуг',
    groupDescription: 'Картинки карточек услуг, используются на главной и странице услуг.',
  },
  {
    key: 'services.card.print',
    label: 'Услуги — широкоформатная печать',
    pageTitle: 'Услуги',
    sectionLabel: 'Карточка услуги',
    usageLabel: 'Изображение карточки «Широкоформатная печать»',
    route: '/services',
    fallbackUrl: '/images/services/printing.png',
    fallbackAlt: 'Широкоформатная печать',
    groupKey: 'services-cards',
    groupLabel: 'Карточки услуг',
    groupDescription: 'Картинки карточек услуг, используются на главной и странице услуг.',
  },
  {
    key: 'services.card.plotter',
    label: 'Услуги — плоттерная резка',
    pageTitle: 'Услуги',
    sectionLabel: 'Карточка услуги',
    usageLabel: 'Изображение карточки «Плоттерная резка»',
    route: '/services',
    fallbackUrl: '/images/services/plotter.png',
    fallbackAlt: 'Плоттерная резка',
    groupKey: 'services-cards',
    groupLabel: 'Карточки услуг',
    groupDescription: 'Картинки карточек услуг, используются на главной и странице услуг.',
  },
  {
    key: 'services.card.thermo',
    label: 'Услуги — печать на футболках',
    pageTitle: 'Услуги',
    sectionLabel: 'Карточка услуги',
    usageLabel: 'Изображение карточки «Печать на футболках»',
    route: '/services',
    fallbackUrl: '/images/services/t-shirt.png',
    fallbackAlt: 'Печать на футболках',
    groupKey: 'services-cards',
    groupLabel: 'Карточки услуг',
    groupDescription: 'Картинки карточек услуг, используются на главной и странице услуг.',
  },
  {
    key: 'services.card.mugs',
    label: 'Услуги — печать на кружках',
    pageTitle: 'Услуги',
    sectionLabel: 'Карточка услуги',
    usageLabel: 'Изображение карточки «Печать на кружках»',
    route: '/services',
    fallbackUrl: '/images/services/glasses.png',
    fallbackAlt: 'Печать на кружках',
    groupKey: 'services-cards',
    groupLabel: 'Карточки услуг',
    groupDescription: 'Картинки карточек услуг, используются на главной и странице услуг.',
  },
  {
    key: 'services.card.stands',
    label: 'Услуги — стенды',
    pageTitle: 'Услуги',
    sectionLabel: 'Карточка услуги',
    usageLabel: 'Изображение карточки «Изготовление стендов»',
    route: '/services',
    fallbackUrl: '/images/services/stends.png',
    fallbackAlt: 'Изготовление стендов',
    groupKey: 'services-cards',
    groupLabel: 'Карточки услуг',
    groupDescription: 'Картинки карточек услуг, используются на главной и странице услуг.',
  },
  {
    key: 'services.card.outdoor',
    label: 'Услуги — наружная реклама',
    pageTitle: 'Услуги',
    sectionLabel: 'Карточка услуги',
    usageLabel: 'Изображение карточки «Наружная реклама»',
    route: '/services',
    fallbackUrl: '/images/services/outdoor.png',
    fallbackAlt: 'Наружная реклама',
    groupKey: 'services-cards',
    groupLabel: 'Карточки услуг',
    groupDescription: 'Картинки карточек услуг, используются на главной и странице услуг.',
  },
  {
    key: 'services.card.polygraphy',
    label: 'Услуги — полиграфия',
    pageTitle: 'Услуги',
    sectionLabel: 'Карточка услуги',
    usageLabel: 'Изображение карточки «Визитки и флаеры»',
    route: '/services',
    fallbackUrl: '/images/services/cards.png',
    fallbackAlt: 'Полиграфия',
    groupKey: 'services-cards',
    groupLabel: 'Карточки услуг',
    groupDescription: 'Картинки карточек услуг, используются на главной и странице услуг.',
  },
  {
    key: 'outdoor.hero.main',
    label: 'Наружная реклама — главный экран',
    pageTitle: 'Наружная реклама',
    sectionLabel: 'Первый экран',
    usageLabel: 'Ключевая иллюстрация страницы услуги «Наружная реклама»',
    route: '/outdoor-advertising',
    fallbackUrl: '/images/outdoor_advertising/manufacturing.png',
    fallbackAlt: 'Производство наружной рекламы',
    groupKey: 'outdoor',
    groupLabel: 'Наружная реклама',
    groupDescription: 'Главные изображения страницы наружной рекламы.',
  },
  {
    key: 'production.hero.main',
    label: 'Производство — главный экран',
    pageTitle: 'Производство',
    sectionLabel: 'Первый экран',
    usageLabel: 'Ключевая иллюстрация страницы услуги «Производство»',
    route: '/production',
    fallbackUrl: '/images/production/hero.png',
    fallbackAlt: 'Собственное производство рекламы',
    groupKey: 'production',
    groupLabel: 'Производство',
    groupDescription: 'Главные изображения страницы «Производство».',
  },
  {
    key: 'production.equipment.milling',
    label: 'Производство — оборудование: фрезер',
    pageTitle: 'Производство',
    sectionLabel: 'Наше оборудование',
    usageLabel: 'Карточка оборудования «Фрезерный станок»',
    route: '/production',
    fallbackUrl: '/images/production/milling.png',
    fallbackAlt: 'Фрезерный станок',
    groupKey: 'production',
    groupLabel: 'Производство',
    groupDescription: 'Главные изображения страницы «Производство».',
  },
  {
    key: 'production.equipment.printer',
    label: 'Производство — оборудование: принтер',
    pageTitle: 'Производство',
    sectionLabel: 'Наше оборудование',
    usageLabel: 'Карточка оборудования «Широкоформатный принтер»',
    route: '/production',
    fallbackUrl: '/images/production/printer.png',
    fallbackAlt: 'Широкоформатный принтер',
    groupKey: 'production',
    groupLabel: 'Производство',
    groupDescription: 'Главные изображения страницы «Производство».',
  },
  {
    key: 'production.equipment.plotter',
    label: 'Производство — оборудование: плоттер',
    pageTitle: 'Производство',
    sectionLabel: 'Наше оборудование',
    usageLabel: 'Карточка оборудования «Плоттерная резка»',
    route: '/production',
    fallbackUrl: '/images/production/plotter.png',
    fallbackAlt: 'Плоттерная резка',
    groupKey: 'production',
    groupLabel: 'Производство',
    groupDescription: 'Главные изображения страницы «Производство».',
  },
  {
    key: 'production.equipment.baget',
    label: 'Производство — оборудование: багетная мастерская',
    pageTitle: 'Производство',
    sectionLabel: 'Наше оборудование',
    usageLabel: 'Карточка оборудования «Багетная мастерская»',
    route: '/production',
    fallbackUrl: '/images/production/bagget.png',
    fallbackAlt: 'Багетная мастерская',
    groupKey: 'production',
    groupLabel: 'Производство',
    groupDescription: 'Главные изображения страницы «Производство».',
  },
  {
    key: 'stands.hero.main',
    label: 'Стенды — главный экран',
    pageTitle: 'Стенды',
    sectionLabel: 'Первый экран',
    usageLabel: 'Главное изображение страницы услуги «Стенды»',
    route: '/services/stands',
    fallbackUrl: '/images/stands/hero.png',
    fallbackAlt: 'Изготовление информационных стендов',
    groupKey: 'service-pages',
    groupLabel: 'Другие страницы услуг',
    groupDescription: 'Ключевые картинки узкоспециализированных страниц услуг.',
  },
  {
    key: 'mugs.hero.main',
    label: 'Кружки — главный экран',
    pageTitle: 'Печать на кружках',
    sectionLabel: 'Первый экран',
    usageLabel: 'Главное изображение страницы услуги «Печать на кружках»',
    route: '/services/mugs',
    fallbackUrl: '/images/mug/mug-hero.jpg',
    fallbackAlt: 'Печать на кружках — пример готовой работы',
    groupKey: 'service-pages',
    groupLabel: 'Другие страницы услуг',
    groupDescription: 'Ключевые картинки узкоспециализированных страниц услуг.',
  },
];

export const SITE_IMAGE_SLOT_KEYS = new Set(SITE_IMAGE_SLOTS.map((slot) => slot.key));
