CREATE TABLE "PublicUploadQuota" (
  "id" TEXT NOT NULL,
  "count" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PublicUploadQuota_pkey" PRIMARY KEY ("id")
);
